### ISSUE TITLE
Please add DAI to loopring_rest_sample.py

### ISSUE THREAD

**Issue by ChristophSiegenthaler** [Loopring/hello_loopring#6]
Thanks :)

**Comment by yueawang** [comment]
Hi, @ChristophSiegenthaler 
Have you solved this problem? You can easily enable DAI by add below line:
`"DAI": {"tokenId":5,"symbol":"DAI","decimals":18}`
to market_info_map in loopring_rest_sample.py. 

You can find all token info by query `https://api.loopring.io/api/v2/exchange/tokens` and add them freely, which is the recommended way.

If you meet a problem, please let me know, thanks!

**Comment by ChristophSiegenthaler** [comment]
Hi @yueawang! Thanks, that worked indeed now. I also managed to place orders with the script in the DAI-ETH pair. When I cancel the order by script, the script tells me "success {'resultInfo': {'code': 0, 'message': 'SUCCESS'}, 'data': True}" but it doesn't actually cancel the order. Otherwise, smooth experience, thanks!

**Comment by ChristophSiegenthaler** [comment]
After I cancel the order manually on loopring I can call the same python call again and the output is still "success"...

**Comment by yueawang** [comment]
Have you specified the orderid using -O?? like
`python trading/trading_example.py -a cancel -O SampleOrder123456789`
or using -H to specify the order hash like
`python trading/trading_example.py -a cancel -H 19082158472221214900403866919498888115075384624459650822137570991225235677571`
Srv always returns success if you cancel a non-exist order, so I guess the Srv does not found the order, you can check the orderid or hash, any problem, please tell me.
Thanks!

**Comment by ChristophSiegenthaler** [comment]
I specified the orderid with -O.
I took the orderid from the output of the "-a add" command and the order was visible in the loopring interface but I couldn't cancel it with "-a cancel". Should I file a new Issue?

**Comment by yueawang** [comment]
I added DAI to the code base, so this issue can be closed. Could you pull codebase and try if the newest works?
If you still meet the problem, let's open a new issue to track that.
BTW: sometimes UI may not refresh in-time, you may need to refresh the web page to see if the order gets canceled after the command line says success.
